[package]
name = "tmkms-nitro-enclave"
version = "0.1.0"
authors = [ "Tomas Tauber <2410580+tomtau@users.noreply.github.com>" ]
edition = "2018"

[dependencies]
ed25519 = { version = "1", features = [ "serde" ] }
secrecy = { version = "0.7", features = [ "serde" ] }
serde = { version = "1", features = [ "derive" ] }
tendermint = { version = "0.17" }
thiserror = "1"
tmkms-light = { path = "../../.." }
zeroize = "1"
